# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/jnb',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/jnb',
                'lib_path': 'jnb'},
  'syms': {'jnb.core': {'jnb.core.foo': ('core.html#foo', 'jnb/core.py')}}}
